config/routes.rb
Library::Application.routes.draw do
 resources :books do
    resources :reservations, only: [:create, :new] do
      member do
        put :free
      end
    end
  end
  root :to => 'site#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reservations
  
  validates :title, presence: true, uniqueness: true
  validates :authors, presence: true

  validates_with IsbnValidator

  def reservation
    self.reservations.where(state: 'reserved').first
  end
  
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :reservation

  before_validation :make_reserved, on: :create
  
  STATES = %w( free reserved )
  
  validates :book_id, presence: true
  validates :state, inclusion: { in: STATES }
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  validates :book_id, uniqueness: {
          scope: :state,
          message: 'book has been already reserved'
        }, if: "state == 'reserved'"

  def free
    self.update_attributes({state: 'free'})
  end

  private
    
    def make_reserved
      self.state = 'reserved'
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
# the URL:s

# /books
  def index
    @books= Book.all
  end

# /books/:id
  def show
    @book= Book.find(params[:id])
  end

# GET /books:id/edit
  def edit
    @book= Book.find(params[:id])
  end

# GET /books/new
 def new
   @book= Book.new
  end

# POST /books
 def create
   @book= Book.new(params[:book])
   if @book.save
    flash[:notice] = "Book created"
    redirect_to books_path
  else
    render action: :new
  end
 end

  # PUT /books/:id
  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(params[:book])
      flash[:notice] = "Book saved"
      redirect_to book_path(@book)
    else
      render action: :edit
    end
  end

  # DELETE /books/:id
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book deleted"
    redirect_to books_path
  end



end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  
  before_filter :find_book
  
  def new
    @reservation = @book.reservations.new
  end
  
  def create
    @reservation = @book.reservations.new(params[:reservation])
    if @reservation.save
      flash[:notice] = "Book reserved"
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def free
    @reservation = @book.reservations.find(params[:id])
    if @reservation.free
      flash[:notice] = "Book is no longer reserved"
    else
      flash[:error] = "Something went wrong"
    end
    redirect_to book_path(@book)
  end
  
  private
  
  def find_book
    @book = Book.find(params[:book_id])
  end
  
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>

  <% unless @book.errors.empty? %>
    <h2> Failed to save the Book </h2>
  <% @book.errors.full_messages.each do |msg| %>
    <p> <%= msg %> </p>
    <% end %>
  <% end %>
  
  <div>
    Title:<br/>
    <%= f.text_field :title %>
  </div>
  
  <div>
    Authors:<br/>
    <%= f.text_field :authors %>
  </div>
  
  <div>
    ISBN:<br/>
    <%= f.text_field :isbn %>
  </div>
  
  <div>
    Description:<br/>
    <%= f.text_area :description %>
  </div>
  
  <%= f.submit "Save" %>
  or
  <%= link_to "Cancel", books_path %>

<% end %>

app/views/books/edit.html.erb
<h1>Edit <%= @book.title %></h1>

<%= render partial: 'form' %>

app/views/books/index.html.erb
<h1> Books </h1>

<p>
  <%= link_to "Add a book", new_book_path %>
</p>

<ul> 
  <% @books.each do  |book| %>
    <li>
      <strong> <%= link_to book.title, book_path(book) %> </strong>
  by <%= book.authors %>
    </li>
 <% end %>
</ul>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render partial: 'form' %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<p>
  by <%= @book.authors %>
</p>

<p>
  ISBN: <%= @book.isbn %>
</p>

<p>
  <%= @book.description %>
</p>

<p>
  <%= @book.description %>
</p>

<p>
  <%= link_to "Back to list", books_path %>
</p>

<p>
  <%= link_to "Edit this book", edit_book_path %>
</p>

<p>
  <%= link_to "Delete this book", book_path(@book), method: :delete %>
</p>

<p>
  <%= link_to "Reserve", new_book_reservation_path(@book) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/new.html.erb
<h1>New reservation for "<%= @book.title %>"</h1>

<%= form_for [@book, @reservation] do |f| %>
  
  <% unless @reservation.errors.empty? %>
    <h2>Failed to save reservation</h2>
    <% @reservation.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  <% end %>
  
  <div>
    Email:<br/>
    <%= f.text_field :email %>
  </div>

  <%= f.submit "Save" %>
  or
  <%= link_to "Cancel", book_path(@book) %>
  
<% end %>

app/views/site/index.html.erb
<h1>Library</h1>
<p>The Library will be open in 8 weeks or so... </p>